Multithreading 02
Alex-Korzun/Mutithreading pull request #2
Opened 2021-02-24 13:52 UTC by Alex-Korzun

2021-02-24 15:08 UTC, vlykhvar approved these changes

2021-02-24 15:08 UTC, vlykhvar commented on logs.log
> +15:34:30,695 INFO  RunnableExample:20 - Runnable example finished working...
here we don't need previous logs. Should clear file before run application

2021-02-24 15:08 UTC, vlykhvar commented on src/test/java/multithreading/practice/second/SummingByCallableTest.java
> +}
need to add new line

2021-02-24 15:08 UTC, vlykhvar commented on src/test/java/multithreading/practice/second/SummingByForkJoinTest.java
> +}
need to add new line

2021-02-24 15:10 UTC, Alex-Korzun commented on logs.log
> +15:34:30,695 INFO  RunnableExample:20 - Runnable example finished working...
agree. just forgot to remove them.

2021-02-24 15:10 UTC, Alex-Korzun commented on src/test/java/multithreading/practice/second/SummingByCallableTest.java
> +}
done

2021-02-24 15:10 UTC, Alex-Korzun commented on src/test/java/multithreading/practice/second/SummingByForkJoinTest.java
> +}
done

2021-02-24 16:13 UTC, Sofasmile requested changes

2021-02-24 16:13 UTC, Sofasmile commented on src/main/java/multithreading/practice/second/SummingUtil.java
> +public class SummingUtil {
якщо ми цей метод використовуємо виключно для тестування, то варто перенести його в папку з тестами. Якщо ж ми використовуємо в коді, то тоді не зовсім зрозуміло для чого тут метод getSum(), адже клас повинен мати єдину зону відповідальності

2021-02-24 16:13 UTC, Sofasmile commented on src/test/java/multithreading/practice/second/SummingByCallableTest.java
> +    public void testSummingByCallable() {
на майбутнє, при виконанні тестових завдань, якщо доведеться покривати код тестами, то варто врахувати якомога більше тестових випадків
для даного завдання можна залишити як є

2021-02-24 17:07 UTC, Alex-Korzun commented on src/test/java/multithreading/practice/second/SummingByCallableTest.java
> +    public void testSummingByCallable() {
got it. thanks

2021-02-24 17:27 UTC, Alex-Korzun commented on src/main/java/multithreading/practice/second/SummingUtil.java
> +public class SummingUtil {
moved method to tests

2021-02-25 08:00 UTC, Sofasmile approved these changes

2021-02-25 16:32 UTC, merged